(asdf:defsystem clpp
  :name "clpp"
  :version "1"
  :maintainer "codr7"
  :author "codr7"
  :description ""
  :licence "MIT"
  :depends-on ()
  :serial t
  :components ((:file "clpp")
	       (:file "util")
	       (:file "location")
	       (:file "deque")
	       (:file "namespace")
	       (:file "form")
	       (:file "read")
	       (:file "repl")
	       (:file "type")
	       (:file "std")))
